# Generated by Django 4.0.5 on 2023-03-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Img',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
    ]
