# Generated by Django 4.0.5 on 2023-03-26 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0003_post_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-tp']},
        ),
        migrations.AddField(
            model_name='post',
            name='tp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
