# Generated by Django 4.0.5 on 2023-03-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_remove_post_height_field_remove_post_width_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/11.jpg', null=True, upload_to='images/'),
        ),
    ]
