# Generated by Django 4.0.5 on 2023-03-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0009_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/images/moon.jpg', null=True, upload_to='images/'),
        ),
    ]
