# Generated by Django 4.0.5 on 2023-04-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0013_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images12/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images/'),
        ),
    ]
