# Generated by Django 4.0.5 on 2023-04-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0015_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='foo', max_length=100),
        ),
    ]
