# Generated by Django 4.0.5 on 2023-04-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0017_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('social', 'social'), ('sciTech', 'sciTech'), ('environment', 'environment'), ('foreign', 'foreign'), ('economic', 'economic'), ('other', 'other')], default='1', max_length=20),
        ),
    ]
